### ISSUE TITLE
Персистентное хранилище для комнат

### ISSUE THREAD

**Issue by kimrgrey** [kimrgrey/webrtc-test-service#5]
Подключить  MongoDB. Пригодится и для чата.

**Comment by dmitrytoropchin** [comment]
Сделал хранение чаткомнат в базе данных MongoDB. Для настройки параметров подключения приделал конфигурацию через [nconf](https://github.com/indexzero/nconf).

**Comment by kimrgrey** [comment]
Не забудь сервак допинать в этом направлении: поставить mongo и сконфигурировать.

**Comment by dmitrytoropchin** [comment]
уже все бегает

**Comment by kimrgrey** [comment]
Тогда, видимо, закрываю :)
