### ISSUE TITLE
Чат на WebSocket

### ISSUE THREAD

**Issue by kimrgrey** [kimrgrey/webrtc-test-service#6]
Замутить чат, чтобы можно было общаться, если что-то пошло не так.

**Comment by dmitrytoropchin** [comment]
Текстовый чат готов, уже бегает на сервере.

Сообщения летают через websocket и хранятся только на клиентах до момента выхода из комнаты.

Да, и выглядит как :hankey:

**Comment by kimrgrey** [comment]
Там после каждого сообщения мерцает связь :)

**Comment by dmitrytoropchin** [comment]
> Там после каждого сообщения мерцает связь :)

А поподробнее?

**Comment by kimrgrey** [comment]
Ну, мы с Серегой созвонились, пока разговаривали - начали писать сообщение. При каждой отправки сообщения мигает видео, как будто отключается на секунду.

**Comment by dmitrytoropchin** [comment]
Принято. Вечером покопаюсь. Вчера у себя вроде такого не заметил.

**Comment by dmitrytoropchin** [comment]
Ну в целом, там какая-то мешанина с redux состоянием и рендерингом страницы `ConferencePage`. В итоге обновление состояния в части сообщений `state.conference.messages` приводит к перерисовке всей страницы. И это меня печалит :worried:

**Comment by kimrgrey** [comment]
`shouldComponentUpdate`? https://facebook.github.io/react/docs/advanced-performance.html

**Comment by dmitrytoropchin** [comment]
поборол :triumph:
