### ISSUE TITLE
Конфигурирование видео / аудио

### ISSUE THREAD

**Issue by kimrgrey** [kimrgrey/webrtc-test-service#7]
Добавить возможность в конфиге выбирать качество и прочие характеристики

**Comment by dmitrytoropchin** [comment]
Добавил в конфигурационный файл клиентского приложения новую секцию `mediaConstraints`:

```
"mediaConstraints": {
  "audio": true,
  "video": {
    "width": {
      "ideal": 1280,
      "max": 1920
    },
    "height": {
      "ideal": 720,
      "max": 1080
    },
    "facingMode": "user",
    "frameRate": {
      "ideal": 24,
      "max": 30
    }
  }
}
```

По умолчанию, запрашиваем аудио и видео в разрешении 720p с максимумом до 1080p с частотой кадров 24 (максимум 30).

**Comment by kimrgrey** [comment]
Отлично 👍  В идеале надо будет потом вытянуть это вообще в ручки на клиенте, чтобы можно было конфигурировать на лету. Но это потом :-)
